### ISSUE TITLE
A typo on one of your Stack Exchange answers

### ISSUE THREAD

**Issue by austinhuang0131** [davibarreira/davibarreira#1]
Apologies for writing an issue here. On [this question](https://math.stackexchange.com/questions/3752685/proving-transient-and-recurring-states-of-markov-chains), you wrote in your response

$\lbrace T_j=k\rbrace = \lbrace X_0\neq k,...,X_{k-1}\neq k, X_k = k\rbrace$

But shouldn't it be this?

$\lbrace T_j=k\rbrace = \lbrace X_0\neq j,...,X_{k-1}\neq j, X_k = j\rbrace$

**Comment by davibarreira** [comment]
Yep, that's it. I'll fix the answer. cheers
